### PR TITLE
Improve tox/pytest config

### PR DESCRIPTION
**Pull request by blueyed**

### CODE REVIEW

**Comment by abingham** [comment]
Is it best practice to use tox.ini in favor of pytest.ini? I'm a complete noob to tox, so I need to learn this stuff!

**Comment by blueyed** [comment]
I prefer to use `tox.ini` only for tox, and then `setup.cfg` for everything else.
I can change this accordingly, and would then also move the `flake8` section there.

**Comment by abingham** [comment]
@blueyed Any idea why github is saying that "All checks have failed"? It looks like [travis build #620](https://travis-ci.org/sixty-north/cosmic-ray/builds/307496068) was the latest build for this PR and passed.

**Comment by blueyed** [comment]
No, rebased now.

**Comment by abingham** [comment]
This looks great. Thanks for taking the time to work through this!

**Pull request merged**
