### PR TITLE
Add git-branch config

### PR DESCRIPTION
**Pull request by ptitpoulpe**
Add a new 'git-branch' config.
If a branch is given, new code in modules will be mutated

### CODE REVIEW

**Comment by abingham** [comment]
It looks like this could be implemented as filter:

https://cosmic-ray.readthedocs.io/en/latest/filters.html

If so (and if there's no strong reason not to), then that's how this should be done. I think we'll find that an extrinsic, filter-based approach is more powerful anyway...we can grow its complexity arbitrarily without needing to touch the CR core.

**Comment by ptitpoulpe** [comment]
ok I will do it like as a filter, but it could be faster to put filter in init to filter before mutation.

**Comment by abingham** [comment]
> but it could be faster to put filter in init to filter before mutation.

Mutation only happens in the `exec` phase. Since you'll (presumably) run your filter after `init` but before `exec`, you will be doing filtering before mutation.

So while your `init` + filter phase might be slightly longer, I don't think you'll see any substantial speed problems overall.

**Comment by ptitpoulpe** [comment]
Make it a filter, will update doc

**Comment by ptitpoulpe** [comment]
Doc added

**Comment by abingham** [comment]
This all look great, thanks!

**Pull request merged**
