### PR TITLE
add exception swallow operator

### PR DESCRIPTION
**Pull request by drorasaf**
I tried to find but couldn't what are the coding conventions for the repository.

### CODE REVIEW

**Comment by drorasaf** [comment]
#206

**Comment by abingham** [comment]
> I tried to find but couldn't what are the coding conventions for the repository.

There's nothing official. If you follow PEP8 you'll be in good shape. Also, try to follow what you see in the rest of the code.

**Comment by abingham** [comment]
I don't think this is what is meant by "exception swallowing" in general. I know what you've submitted closely matches what mutpy does, but I think that model is wrong. In my understanding, exception swallowing should add a `try...exception` around a body of code which prevents any exceptions from escaping. 

What your operator does is effectively delete an arbitrary body of code in an exception handler. This is problematic because it makes it very hard to determine *why* a mutant is killed.

Also, the behavior of your operator doesn't really match its name. It's not (necessarily) swallowing any exception; it's just gutting their handlers.

**Comment by drorasaf** [comment]
My idea was to take the exception handler and remove the code handling inside of it, which is similar to the situation where we take `try: expr1 exception: expr2`, and try to verify that `expr2` has significance in tests.

If you think it is better I can make the operator work for the following use case:
`try: expr1 exception: expr2 exception: expr3` -->`try: expr1 exception: expr3

**Comment by abingham** [comment]
Right, I see the intent of your operator, but I'm not convinced that it's the right thing to do. First, even if this is a mutation that we want, it should not be called "exception swallow" because it doesn't do that. Rather, it removes the content of an exception handler. This isn't quite the same as "exception handler deletion" because the handler is still there, it just doesn't do anything. Maybe it should be called "exception handler clearing".

Second, I'm not convinced that the mutation is helpful. Ultimately, it replaces an unbounded amount of code with `pass`, giving the user very little information about *why* the mutation causes a failure (or success, for that matter). Most mutations are small in nature, and this one just feels "too big". I feel like its overshadowed by the mutation that will happen anyway to the code in the `except` block, ie any benefit from this operator may already be found in existing operators.

I am open to being convinced that this operator is worth including, so by all means see if there's a good motivating example. Maybe there's a reference in some mutation testing literature, or maybe the mutpy author can provide some details (since s/he seems to do what you're doing). But I'm largely convinced that your operator needs a new name.

Also, I hope I'm not discouraging you too much. I sincerely appreciate your work on this, and I look forward to eventually integrating your work into the project.

**Comment by drorasaf** [comment]
The main motivation for mutation testing is to provide stability measure for the unit tests of a given project. Since one of the main issues in code is error handling, the basic goal to verify exception handling does matter.

I agree that I can change the implementation, even if I change it to `try expr1 except: expr2` --> `expr1`, the mutation will be quite big as well.

Don't worry, I'm not discouraged so easily, I have a pipeline of operators;), if you have any new ideas I will be happy to hear.
Current pipeline:
1. Exception handler deletion - causing exception propagation
2. Change Except to another
3. remove decorator from function- excluding static and class decorators,
4. remove decorator from class
5. zero iteration loop - For/While

**Comment by abingham** [comment]
> Don't worry, I'm not discouraged so easily

That's good :) The work you've done so far is great, and I'm really glad to have capable contributors.

> Since one of the main issues in code is error handling, the basic goal to verify exception handling does matter.

I completely agree, and I fully support operators that mutate error-handling code in useful ways. But I'm not (yet) sure that removing an `except-block`'s body is very useful. 

I try to look at it from the user's point of view. Suppose I have 100 lines of code in some `except-block` and CR replaces it with `pass`. If mutant survives I don't know very much. Was the exception never thrown? Which parts of the removed code weren't properly tested? Was it the removal of certain interoperating lines that mattered? Who knows. That's why I think that other mutation operators working in the removed body tell us more.

Similarly, if the mutant is killed, I don't know a lot either. Generally, I would expect *any* reasonable set of tests to fail if an arbitrary 100 line code-block were removed from my code, so I'm hesitant to add operators that do that.

**Comment by abingham** [comment]
> I have a pipeline of operators

All of those sound good!

**Comment by drorasaf** [comment]
> Btw check out this video. It talks about research on exception/error handling code and mentions several very common mistakes. It's been on my todo list for quite a while but I haven't gotten the time to work on it:
https://www.youtube.com/watch?v=56oNQf5oITw&t=785s&list=PLFjlI7p-h1hxBP3cIjEqePSeoBDHud5Db&index=55
> 
As @atodorov  mentioned, this provides a very good motivation, since many times the exception handling is either non existent or incorrect. Usually exception handling should not consist of 100 lines of code, especially in python;)

These projects had major bugs which were the result of trivial error handling issues.

**Comment by abingham** [comment]
> this provides a very strong motivation

I don't disagree that defects in error handling are both common and serious. What I'm concerned about is introducing operators that don't add to CRs ability to detect inadequate test suites (which is all that CR really does). 

> Usually exception handling should not consist of 100 lines of code, especially in python;)

If you're starting from the (correct) position that "many times the exception handling is either non existent or incorrect", you need to also accept that many programmers will happily create except block like that. I chose 100 lines arbitrarily, but the point is that we can't assume that CR is running over optimal, beautiful code. And in any case, what number should it be? I don't think it's any more helpful to delete 10 lines than 100.

If we're going to provide operators that remove blocks of code, why would we stop at except blocks? Why not loop bodies or function bodies? These strike me as obviously nonsensical: of *course* that would cause a test failure with any meaningful test suite. But I don't see how that's any different from removing except block bodies.

A fair criticism of my position is that I'm perfectly happy to allow an operator to remove an entire except clause, even if its body is large. This feels critically different to me, however, than removing just the body because of the core change in behavior.

**Comment by drorasaf** [comment]
I think that the more we talk about it, the more I think it is better to ignore this pull request and to move to change the exception handler type, which creates minimal change with the same outcome.

**Comment by abingham** [comment]
That sounds good to me. Close this out if you decide to go that way.

**Pull request closed without merging**
